// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouecqallepfgsbvpwqat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZWNxYWxsZXBmZ3NidnB3cWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDIyNDMsImV4cCI6MjA2MTk3ODI0M30.TYdpYA97h5JBYqj2quMNE5esSNltet88yrLvM1HIN1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);